document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("	<meta charset=\"utf-8\">");
document.writeln("	<link rel=\"stylesheet\" type=\"text/css\" href=\"18css.css\">");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\"bo_bar\"><img src=\"https://13511974.s21i.faiusr.com/4/10/ABUIABAEGAAg-My8rwYozLjCmAIw6gI4owE.png\" height=\"50px\"><p>|&nbsp&nbsp&nbsp© 2020-2022&nbsp&nbsp&nbsp|&nbsp&nbsp&nbsp网站设计与维护：春潮信息&nbsp&nbsp&nbsp|</p></div>");
document.writeln("</body>");
document.writeln("</html>");