document.writeln("<!DOCTYPE html>");
document.writeln("<html class=\"gfjs3main\">");
document.writeln("<head>");
document.writeln("	<meta charset=\"utf-8\">");
document.writeln("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
document.writeln("	<style type=\"text/css\">");
document.writeln("		body {margin:0;padding:0;}");
document.writeln("		@media (max-width:762px) {");
document.writeln("			.gfjspcbody {display:none}");
document.writeln("			.gfjsmobilebody {margin:30px;text-align:center;line-height:300%;font-size:30px;color:#9F5000;border:1px solid #9F5000;background-image:linear-gradient(to top,#FFEEDD,#FFFAF4);}");
document.writeln("		} ");
document.writeln("");
document.writeln("		@media (min-width:762.1px) {");
document.writeln("			.gfjspcbody {background:#F7F9FB;}");
document.writeln("			.shiyongsm {margin:30px;padding:0 20px;border:2px dotted red;font-size:14px;line-height:230%;font-family:Tahoma,宋体,sans-serif;}");
document.writeln("			.gfjsmobilebody {display:none}");
document.writeln("			.gfqrbtn {background-image:url(\'https://13511974.s21i.faiusr.com/2/10/ABUIABACGAAgvoPRrwYooMnHrAUwQTgX.jpg\');font-size:12px;text-align: center;padding:5px 10px;border: none;background-size:100% 100%;color:#104f7a;}");
document.writeln("		} ");
document.writeln("");
document.writeln("	</style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\"gfjspcbody\">");
document.writeln("<img src=\"https://13511974.s21i.faiusr.com/4/10/ABUIABAEGAAgsP-QrwYo0Mjh0QIw5Q04iQI.png\" width=\"100%\">");
document.writeln("<div class=\"shiyongsm\"><span><b>使用说明：</b></span>输入春潮投稿管理客服回复您的邮件中的流水号，查询您的稿费。在没有异议后进行稿费确认结算。</div>");
document.writeln("<iframe allow=\"clipboard-read\;clipboard-write\" frameborder=\"no\" border=\"0\" marginwidth=\"0\" marginheight=\"0\" allowtransparency=\"yes\" style=\"width:100%;min-height:240px;\" src=\"https://d5ro1v7d.yichafen.com/embed/queryscore/sqcode/NsTcMn4mNTgxNnxhYTk2M2M1ZWJjOWFhNDc4OGMzNDdlYjMyNmU2MTIwMnxkNXJvMXY3ZAO0O0OO0O0O.html\"></iframe>");

document.writeln("</div>");
document.writeln("<div class=\"gfjsmobilebody\">本系统暂不支持使用移动设备访问！请使用PC访问。</div>");
document.writeln("</body>");
document.writeln("</html>");
