document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("	<meta charset=\"utf-8\">");
document.writeln("	<link rel=\"stylesheet\" type=\"text/css\" href=\"18css.css\">");
document.writeln("    <link rel=\"stylesheet\" href=\"https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css\">");
document.writeln("    <script src=\"https://cdn.staticfile.net/jquery/2.1.1/jquery.min.js\"></script>");
document.writeln("    <script src=\"https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js\"></script>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\"yqljbtn\" onclick=\"window.location.href=\'#\'\">签约稿费结算(停用)</div>");
document.writeln("        <div class=\"yqljbtn\" onclick=\"window.location.href=\'#\'\">单投稿费结算(停用)</div>");
document.writeln("        <div class=\"yqljbtn\" onclick=\"window.location.href=\'#\'\">广告分成管理平台(停用)</div>");
document.writeln("        <div class=\"yqljbtn\" onclick=\"window.location.href=\'h-jb.htm\'\">侵权内容举报</div>");
document.writeln("        <div class=\"yqljbtn\" onclick=\"window.location.href=\'h-tg.htm\'\">专栏投稿</div>");
document.writeln("        <div class=\"yqljbtn\" onclick=\"window.location.href=\'/h-news-49.htm\'\">信息公开</div>");
document.writeln("        <div class=\"yqljbtn\" onclick=\"window.location.href=\'h-gfjs3.htm\'\">新版稿费结算</div>");
document.writeln("</body>");
document.writeln("</html>");